version: '3'

services:
  stellar:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      network: host
      args:
        - VARIANT=22.04
    image: stellar:latest
    container_name: stellar
    working_dir: /workspace
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 505:505
    volumes:
      - .:/workspace:cached
    secrets:
      - ssh_public_key
      - ssh_private_key
      - gitconfig
      - kaggle_json

# Runtime secrets used by the Docker service(s)
secrets:
  ssh_public_key:
    file: ~/.ssh/id_ed25519_github.pub
  ssh_private_key:
    file: ~/.ssh/id_ed25519_github
  gitconfig:
    file: ~/.gitconfig-personal
  kaggle_json:
    file: ~/Repos/personal/kaggle.json
